# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 166e085e65202631f2d98dc426b3ce58fdb3ce14998010d5cca6c519d75f8b2112dfab7dc9ed8bcd37032e56bc89cf3f30647631f6358da5d4334b8ee2a265d7

test:
  secret_key_base: c81ea2ef89aba1d9e1e890a33b03ed5e5fd7e641626a23b0654576e74cdb634ab5d94cd1ee104e0fc554269160aaa2ebec275d1de498eb8c17b24f61e14f2161

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
